imports:
  - { resource: forms.yml }

parameters:
#    al3asema_backend.example.class: Al3asema\BackendBundle\Example

services:
#    al3asema_backend.example:
#        class: %al3asema_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    listing_crawler:
        class: Al3asema\CrawlerBundle\Crawlers\BaseCrawler
        arguments: ['@doctrine.odm.mongodb.document_manager']

