imports:
  - { resource: forms.yml }

parameters:
#    amaged_backend.example.class: AMaged\BackendBundle\Example

services:
#    amaged_backend.example:
#        class: %amaged_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    listing_crawler:
        class: AMaged\CrawlerBundle\Crawlers\BaseCrawler
        arguments: ['@doctrine.odm.mongodb.document_manager']

